version: '3'
services:
  # public-facing ssh host
  bastion:
    build: ssh
    image: playground-ssh
    ports:
      - "2222:22"

  # cli tool
  rundeck-cli:
    build:
      context: rundeck-cli
      args:
        COMMIT: 6aeb65b9085c1d5811163a25c15fe278d34fd846
    image: playground-rundeck-cli
  
  # plugin bootstrap tool
  rundeck-plugin-bootstrap:
    build:
      context: rundeck-plugin-bootstrap
      args:
        COMMIT: 3b5783ec795386d70d52f30f5581466d76aa10b6
    image: playground-rundeck-plugin-bootstrap

  # backend
  database:
    build: database
    image: playground-database
    volumes:
        - db-data:/var/lib/postgresql/data

  # middle tier
  web_1:
    build: web
    image: playground-web
  web_2:
    build: web
    image: playground-web

  # public-facing http proxy
  loadbalancer:
    build: loadbalancer
    image: playground-loadbalancer
    ports:
      - "8080:80"

  # rundeck server
  rundeck:
    build: rundeck
    image: playground-rundeck
    ports:
      - "4440:4440"
    volumes:
      - rundeck-data:/home/rundeck/server/data
    command: -Drundeck.features.repository.enabled=true

  # packager host
  fpm:
    build: fpm
    image: playground-fpm

  # fake s3 api
  fakes3:
    image: lphoward/fake-s3

volumes:
  rundeck-data:
  db-data: