- name: UpdateAppConfig
  uuid: UpdateAppConfig
  group: DB Credential Rotation
  nodefilters:
    filter: web_.*
  options:
  - label: Database user
    name: dbuser
    required: true
  scheduleEnabled: true
  sequence:
    commands:
    - nodeStep: true
      configuration:
        user: ${option.dbuser}
        password: keys/projects/hello-project/db/${option.dbuser}
      type: UpdateDBCredentials
    keepgoing: false
    strategy: node-first
