# yaml plugin metadata

name: Hello world with args
version: 1
rundeckPluginVersion: 1.2
author: Carlo Cabanilla
date: 2018-07-20
url: http://rundeck.org/
providers:
  - name: HelloBash
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: helloworld.sh
    script-args: ${job.name}

  - name: RestartApp
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: restart.sh
    script-args: ${config.process} ${config.health_url}
    config:
      - type: String
        name: process
        title: process
        description: the process to restart
      - type: String
        name: health_url
        title: health_url
        description: the http endpoint to poll to check that it's healthy
        default: http://localhost:8080

  - name: ChangePassword
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /usr/bin/python3
    script-file: change_password.py
    script-args: /etc/web.yaml ${config.new_user} ${config.new_password}
    config:
      - type: String
        name: new_user
        title: new_user
        description: 'New db user'
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: new_password
        title: new_password
        description: 'New db password'
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"

  - name: CreateDBUser
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: create-db-user.sh
    script-args: ${config.master_db_user} ${config.master_db_password} ${config.new_user} ${config.new_password}
    config:
      - type: String
        name: master_db_user
        title: master_db_user
        description: 'master db user with rights to create new users'
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: master_db_password
        title: master_db_password
        description: 'master db user password'
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: new_user
        title: new_user
        description: 'New db user'
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: String
        name: new_password
        title: new_password
        description: 'New db password'
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"

  - name: HelloGo
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /usr/bin/go run
    script-file: helloworld.go
    script-args: ${job.name}
