# yaml plugin metadata

name: Hello world with args
version: 1
rundeckPluginVersion: 1.2
author: Carlo Cabanilla
date: 2018-07-20
url: http://rundeck.org/
providers:
  - name: HelloBash
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: helloworld.sh
    script-args: ${job.name}

  - name: RestartApp
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: restart.sh
    script-args: ${config.process} ${config.health_url}
    config:
      - type: String
        name: process
        title: process
        description: the process to restart
      - type: String
        name: health_url
        title: health_url
        description: the http endpoint to poll to check that it's healthy
        default: http://localhost:8080

  - name: HelloPython
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /usr/bin/python3
    script-file: helloworld.py
    script-args: ${job.name} /etc/web.yaml

  - name: HelloGo
    service: RemoteScriptNodeStep
    plugin-type: script
    script-interpreter: /usr/bin/go run
    script-file: helloworld.go
    script-args: ${job.name}
